export const materialsCategories = [
  "Doors",
  "Electrical",
  "Hardware",
  "Landscaping",
  "Lumber / Plywood",
  "Masonry",
  "Metal Framing",
  "Mouldings",
  "Painting",
  "Plumbing",
  "Roofing",
  "Steel Bars",
  "Tiles",
  "Tools",
  "Waterproofing",
  "Windows",
  "Waterline",
  "Other",
];
